version: '3'
# Run node-app with nodemon and a bind mount so that server + static changes are synced while running
services:
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: development 
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev